---
title: Response to reviewers
format: pdf
execute: 
  echo: false
  cache: true
  warning: false
  message: false

filters:
  - _extensions/ute/search-replace/search-replace.lua

search-replace:
  +S2: ACCESS-S2
  +S1: ACCESS-S1
  +CDR: NOAA/NSIDC CDRV4


bibliography: references.bib  

editor:
  markdown:
    wrap: sentence

header-includes: |
    \usepackage{etoolbox}
    \usepackage{xcolor}
    \AtBeginEnvironment{quote}{\color[gray]{0.3}}
---



# Reviewer 2

> L219: "Figure Figure 7" -> "Figure 7"

We have corrected this.

> Line 300: What are the differences between Figures A15 and A16? Figure A15 appears to use CDR, while Figure A16 uses OSI. If so, this contradicts Lines 136–137.

Thank you for the correction.
Figures A6, A8, A10, A15 are supplementary figures to illustrate minor points, while the rest are the reproduction of the main figures using the alternate dataset. 
We moved the former group to their own subsection within the Appendix and removed A16, which was wholly redundant. 


# Reviewer 1

> In the revised manuscript, the author attempt to address this concern by showing that the variance of the RMSE within ACCESS-1 and ACCESS-2 is indistinguishable, arguing that ensemble spread is therefore not responsible for the differences in sea-ice prediction performance. However, this only partially addresses my concern, as the use of a logarithmic scale in Figure A15 masks the actual differences between ACCESS-1 and ACCESS-2. 

We used a vertical log scale in Figure A15 so that the differences at the shorter leadtimes were visible. 
@fig-spread-nolog shows a version of that figure without the logarithmic vertical scale to illustrate that at shorter lead times +S1 and +S2 spread look identical. 

```{r}
#| label: fig-spread-nolog
#| fig-cap: Mean variance of RMSE between ensemble members of each forecast. In parentheses, the shortest minimum  lead time at which +S1 mean spread becomes larger than the lower bound of the 95% confidence interval of +S2 spread. Note the double log scale.
#| fig-height: 4
library(rcdo)
library(ggplot2)
library(metR)
library(data.table)

cdo_options_set("-L")
cdo_cache_set(here::here("data/temp/cache"))

source(here::here("R/functions.R"))
source(here::here("R/datasets.R"))
source(here::here("R/ggplot.R"))

readRDS(here::here("data/derived/spread-plot.Rds")) +
  scale_y_continuous("Mean ensemble spread")
```

> In addition, the impact of differences in oceanic initial conditions remains unclear. The authors state in the revised manuscript that “we believe there are reasons to consider that the effect would be of second-order importance.” I do not find this statement sufficiently rigorous to support the conclusion regarding the role of initial conditions in seasonal prediction of Antarctic sea ice. A more quantitative or evidence-based assessment would be necessary to substantiate this claim.

We agree that the role of initial conditions cannot be directly quantified based on our work and that our arguments to support the secondary role of the ocean initial conditions are limited. 
We deliberately use subjective language to make it clear that we don't consider the question settled.  

We modified lines XXX to reflect that limitation more explicitly: "Although we believe these differences to be of second-order importance compared with the wildly divergent sea-ice initial conditions, we cannot rigorously discard nor directly quantify their influence; these issues motivate the need for more targeted experiments. "


> P2 Line 54, Please clarify what is meant by “observed sea ice initial condition”

@xiu2025 analysed hindcasts in which the initial conditions are derived from a data assimilation system, whereas @morioka2022 initialised their runs from observations directly. 
Lines XX now read: "the former initialised the model using observed sea-ice initial conditions while the latter used initial conditions derived from a data assimilation system."

> P2 Line 54, typo asimilatonand

We have corrected this.

> P8 Line 193, This statement could be made more rigorous. Once the oceanic and atmospheric states are altered, such changes will inevitably influence the sea-ice state, even if the magnitude of the impact is small.

We changed the wording to indicate that the "the indirect effect of the ocean and atmosphere data assimilation on sea ice is minimal" instead of "not affecting sea ice". 

> P12 Line 219, double Figure.

We have corrected this.

> Figures: Several figures contain a large number of subplots, which makes it difficult to identifythe key messages. I recommend simplifying the figures and retaining only the panels that convey the essential information.

As we commented on our response to Reviewer 3 in the previous round, while we appreciate the concern, we believe that readers may be interested in seeing the complete evolution of results over the year.
Hence for consistency across all figures and to show the evolution of results over the year we have decided to keep monthly subplots.

# References